# BASIC INFORMATION
# project name
name: Axeon KuroWiki

# Axeon KuroWiki is used in main kurowiki builds
# Axeon Deltari is used in deltari builds
productname: Axeon KuroWiki

# project and site title
title: KuroWiki

# author of work, used in copyright notice
author: Axeon Network

# copyright year
copyyear: "2025-2026"

# your email
email: thenekori64@gmail.com

# description of site, used in embeds
description: "Axeon KuroWiki Beta 6.01"

# the url of your site
url: https://axeon-network.github.io

# baseurl, only use if used on a subdirectory and not website root. prod-kuro *has* to use this
baseurl: /kurowiki

# source code url
sourceurl: "https://github.com/Axeon-Network/kurowiki"

# license name
license: Creative Commons Attribution-ShareAlike 4.0
# license url
licenseurl: https://creativecommons.org/licenses/by-sa/4.0/deed.en
# short license name
license-s: CC-BY-SA-4.0

# image license name
img_license: Creative Commons Attribution International 4.0
# image license url
img_licenseurl: https://creativecommons.org/licenses/by/4.0/deed.en
# short image license name
img_license-s: CC-BY-4.0

# HOMEPAGE
# quick description of your wiki and what is it about, visible on the homepage
home_desc: "This is the home page for KuroWiki. An online encyclopedia about the Axeon Network and its administrators (Nekori and KayAurora)."

# featured article. specify the file name of the article
featuredarticle: lynxmicblog

# retail tag. specifies the version number used in the drawer, and is to be replaced by
# an incrementing one IF the debug mode is enabled.
retailtag: 6.0.4450.main.260110-2027

# THEMING
# your background
# background-dark will be the background appling on dark mode, background-light will apply on light mode
# for this to work, you have to place your background files in resources/img
# leave empty to use the default backgrounds
background-dark:
background-light:

# DEVELOPER/DEBUG
# developer phase
devphase: Beta 6.01

# debug mode
# setting this to true enables the debug kurowiki and springviewer watermarks, 
# and enables the incrementing build number in the drawer alongside a (Debug) suffix to the string above Axeon KuroWiki
debug: false

# retail mode
# enable this for non-developer builds, like public releases or IDRs
# The Two KuroWiki Developers Shall Not Forget This Setting
retail: true

# stupid
myvariable: "{{ site.myvariable }}"

# only ONE of these can be enabled
# ...i mean you can use both, but that wouldnt be practical, would it?
# if you enable neither, you need help

# specifies if text should be used in the drawer
drawertitle: false
# specifies if a banner should be used in the drawer
drawerbanner: true

# more variables to be set in the future!

# liquid you son of a bitch
encoding: "utf-8"

markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# theme: minima
plugins:
  - jekyll-redirect-from

kramdown:
  input: GFM
  hard_wrap: true

exclude:
  - resources/ruby/version # just so it doesnt get caught in a loop
  - resources/ruby/buildtag # ditto
